name: flutter_accept
description: An open source Flutter plugin for calling WeAccept’s native SDK
version: 1.0.0
homepage: https://github.com/tarekmorsi/flutter_accept

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: com.tarekmorsi.flutter_accept
    pluginClass: FlutterAcceptPlugin
